### ISSUE TITLE
Don't working with sails@beta

### ISSUE THREAD

**Issue by CodeFunta** [gengojs/sails-hook-gengojs#2]
Module  doesn't work with sails 1.0 (beta).
Error:
TypeError: core is not a function
    at Domain.<anonymous> (...\**sails-hook-gengojs\lib\index.js:84:14**)
